### ISSUE TITLE
Highlight hostnames

### ISSUE THREAD

**Issue by tijn** [tijn/hosts.tmLanguage#7]
We currently have space grade parsing and highligting code for IP-addresses but the hostnames are simply white.

We could do a better job by highlighting valid hostnames; or in other words, not highlighting "hostnames" that contain invalid characters. I'm pretty sure all of these `~@#$%+=()*&^:;\|/?,<>` have no place in a proper hostname.

See: https://en.wikipedia.org/wiki/Hostname and https://en.wikipedia.org/wiki/Domain_name .

> Hostnames are composed of a series of labels concatenated with dots. For example, "en.wikipedia.org" is a hostname. Each label must be from 1 to 63 characters long,[2] and the entire hostname including the delimiting dots, but not a trailing dot, has a maximum of 253 ASCII characters. [...]

**Comment by michaelblyons** [comment]
I typed up the stuff below... but then I just wrote some code. 😅 


> We currently have space grade parsing and highligting code for IP-addresses but the hostnames are simply white.

I set hostnames to include a `string.unquoted` scope for a while, but I thought you might object, so I took it out. 😉 

> We could do a better job by highlighting valid hostnames; or in other words, not highlighting "hostnames" that contain invalid characters. I'm pretty sure all of these `~@#$%+=()*&^:;\|/?,<>` have no place in a proper hostname.

Right now, it's set to just allow `[\w.-]`, but we can certainly do some more rigorous validation

> See: https://en.wikipedia.org/wiki/Hostname and https://en.wikipedia.org/wiki/Domain_name .
> 
> > Hostnames are composed of a series of labels concatenated with dots. For example, "en.wikipedia.org" is a hostname. Each label must be from 1 to 63 characters long,[2] and the entire hostname including the delimiting dots, but not a trailing dot, has a maximum of 253 ASCII characters. [...]

**Comment by michaelblyons** [comment]
Is it reasonable to consider this "Fixed" ?

**Comment by tijn** [comment]
> Is it reasonable to consider this "Fixed" ?

I think so, yes. 😄
