### ISSUE TITLE
Extreme loading times with long host file

### ISSUE THREAD

**Issue by Nanorithm** [tijn/hosts.tmLanguage#9]
All IP addresses in my hosts file are now showing as invalid (orange) after the 2.0.0 update and the host names are showing as green. Prior to the update, valid IPs were green, invalid were orange, and host names were white.

Not sure what change caused this but it seemed to break everything. Not sure how to downgrade but I'd prefer that over the current version. I did nothing to my Sublime text recently in terms of config, I just booted this morning and it was broken.
 
Example:
![image](https://user-images.githubusercontent.com/13856563/74668073-75a39d80-5172-11ea-85ba-7009f4742d52.png)

Mac OS 10.14.6 Mojave, MacBook Pro 2019, Sublime Text 3 Build 3211

**Comment by tijn** [comment]
@UltimateSky I believe those colours originate from the theme you're using.

For me (see screenshot) local IP addresses turn blue and the other ones are purple. And this is in line with what I see in a random javascript file that I happen to have here before me. Numbers are purple, and strings are yellow.

![image](https://user-images.githubusercontent.com/18674/74668929-80782580-51a6-11ea-89fe-fbef123816b9.png)

Here's a small javascript sample to demonstrate what I mean:

![image](https://user-images.githubusercontent.com/18674/74669581-ba95f700-51a7-11ea-8256-899bc1c9232b.png)

and in Ruby:

![image](https://user-images.githubusercontent.com/18674/74669604-cc779a00-51a7-11ea-9c20-3565fe06d5ad.png)

**Comment by Nanorithm** [comment]
@tijn I see how that could be an issue but I don't see why it would have changed from what was there previously if the theme was not updated. Is there any way to manually configure coloring?

**Comment by tijn** [comment]
@UltimateSky I also don't see how it changed the colours for you. But let's investigate. 

So, what happened is this: #6 It's a big rewrite, hence the major version upgrade.

I think for you, [line 86 in the syntax defninition](https://github.com/tijn/hosts.tmLanguage/pull/6/files#diff-908d221954c24b38624446ed4a912c88R82) is the important line. It tells ST3 to colour the IPv4 address as `constant.numeric.integer.decimal.hosts`.

In the [old definition on line 52](https://github.com/tijn/hosts.tmLanguage/pull/6/files#diff-179618128968796c75e1fdde76518551L52) this used to be `constant.numeric.hosts`. 

Ah, that's probably it. The new definition is more precise. The theme you're using is probably using orange for `constant.numeric.integer` and green for `constant.numeric`. (Note that we don't use any colour names in the syntax definitions; we just provide "meaning" to specific recognized parts of the file at hand. The way you interpreted orange as "wrong" and green as "right" was never our intention. That's just a coincidence.)

**Comment by Nanorithm** [comment]
Ah I see what you mean, thanks. I'll see if I can tweak my theme then.

I also noticed another issue, not sure if I should open a separate issue for it. Whenever I leave my host file to work on something else for a few minutes, when I return to sublime, my host file will reload, with a loading bar. It takes ~5-15s each time. I didn't notice this at all before and I don't notice it when I'm using any other syntax highlighter.

**Comment by michaelblyons** [comment]
> The theme you're using is probably using orange for `constant.numeric.integer` and green for `constant.numeric`. (Note that we don't use any colour names in the syntax definitions; we just provide "meaning" to specific recognized parts of the file at hand. The way you interpreted orange as "wrong" and green as "right" was never our intention. That's just a coincidence.)

The rewrite (and I suspect the original, too) does not mark invalid IPs. It's hard to do that without serious detriment to the UX of typing a new line. (i.e. It's disconcerting to have nasty `invalid.illegal` highlighting when you just typed `127.0.0.` until you type the final `1`.)

> I also noticed another issue, not sure if I should open a separate issue for it. Whenever I leave my host file to work on something else for a few minutes, when I return to sublime, my host file will reload, with a loading bar. It takes ~5-15s each time. I didn't notice this at all before and I don't notice it when I'm using any other syntax highlighter.

That is curious. The unit test has 78 hosts entries and finishes parsing in 1.5-2ms. If you copy your hosts file to a new file with this syntax highlighting and leave that open, does the new file do the same thing? Is the file very long?

**Comment by Nanorithm** [comment]
> That is curious. The unit test has 78 hosts entries and finishes parsing in 1.5-2ms. If you copy your hosts file to a new file with this syntax highlighting and leave that open, does the new file do the same thing? Is the file very long?

I haven't tried with a new file, I can try that tomorrow. But for reference my host file is currently around 2000 lines for work, it was working flawlessly for the past few months, issues only popped up today after the update.

**Comment by Nanorithm** [comment]
@michaelblyons Update: Saving the entries to a new file doesn't cause the same load time, but opening the tab from /etc/hosts is still causing noticeable load time.

Edit: I noticed that while the new file doesn't have a loading bar, occasionally it will just lag and I am unable to do anything for a few seconds.

**Comment by michaelblyons** [comment]
@Nanorithm Understood, thanks. I'll experiment with a larger test file.

If you are willing to post or send me your (potentially obfuscated) hosts file, I can try explicitly with that. If you don't want to post it here, use `github` at `michael.lyö` without the umlaut, and append the New Zealand TLD.

May I also ask if you have a process that `touch`es or otherwise modifies the file in the background? That's typically the cause of ST reloading a file (but it doesn't usually take multiple seconds unless the file is quite long).

**Comment by Nanorithm** [comment]
@michaelblyons I don't think that my personal hosts file would help much after obfuscation (or even otherwise) since all of the entries are NAT IPs specific to the VPN that I am connected to. As of right now, my host file is 2997 lines and I'd estimate ~250-300 lines of that is probably for comments and spacing if that helps at all.

**Comment by Nanorithm** [comment]
Has there been any headway on this yet @michaelblyons @tijn ? It's getting to a point where I'm about to just disable it for now lol. I'd even be satisfied if I could downgrade to the previous version at this point. I understand it taking a few seconds on a fresh open but reloading just from opening the window every 5-10 minutes is starting to get frustrating lol.

**Comment by michaelblyons** [comment]
I'll try to scrape some time together this weekend to look at it. In the meantime, to get the old version back, you can

- Uninstall the package
- `git clone https://github.com/tijn/hosts.tmLanguage.git Hosts` in your Packages directory (wherever _Preferences > Browse packages..._ takes you)
- `git switch 1.1.0`

Once again, sorry about that.

**Comment by michaelblyons** [comment]
I've now tried a 19k-IP file with both the 2017 and new syntax definitions. With assertions (comments), the total file length is 82k lines. The "Performance" of highlighting the files is about 10% slower (267ms to 295ms). 

However, I did see some weird stuff opening other programs and coming back. After some testing, I think it's the hostname indexing for thousands of hosts.

@Nanorithm, before you give up and revert, can you try adding a file named something like `UnindexHostnames.tmPreferences` to your `Packages/User` folder, containing this content:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Symbol List</string>
    <key>scope</key>
    <string>
        text.hosts meta.hostname,
        text.hosts meta.link-local
    </string>
    <key>settings</key>
    <dict>
        <key>showInSymbolList</key>
        <integer>0</integer>
    </dict>
</dict>
</plist>
```

**Comment by Nanorithm** [comment]
@michaelblyons I tried adding your `UnindexHostnames.tmPreferences` file and I'm not noticing any change really. Is there anything additional I need to do besides creating the file and restarting sublime?

**Comment by michaelblyons** [comment]
If you have your hosts file up in ST, does <kbd>Ctrl</kbd>+<kbd>R</kbd> (MacOS: <kbd>Cmd</kbd>+<kbd>R</kbd>) show a list of hostnames in an autocomplete box? We're trying to make that autocomplete empty for you.

In theory, you shouldn't need to restart.

**Comment by Nanorithm** [comment]
Not that I can see, it just shows a textbox with an @ inside, typing doesn't bring up any autocomplete list. I'm on MacOS if that makes any difference.

**Comment by michaelblyons** [comment]
Okay. If your problem is still happening, then it wasn't the hostname index. I'm on MacOS, too. I did reproduce your problem twice in quick succession, but I'm having trouble making it happen again. 😞

**Comment by wbond** [comment]
I'm curious if:

 1. Does this problem happen if the contents of `/etc/hosts` is saved in a separate file and that file is opened in Sublime Text?
 2. Does the problem stop if you use the old syntax definition?

**Comment by wbond** [comment]
Additionally, @Nanorithm, do you have something periodically changing contents of `/etc/hosts`? That is the only reason I can imagine Sublime Text reloading the file when you focus on Sublime Text.

Additionally, have you tried a fresh install to make sure no other packages are causing the issue. If you see a lag, you could try executing the menu item *Tools > Developer > Profile Plugins* and paste the results here.

**Comment by Nanorithm** [comment]
@wbond

> 1. Does this problem happen if the contents of `/etc/hosts` is saved in a separate file and that file is opened in Sublime Text?

It seems like it does happen, but not as frequently

> 2. Does the problem stop if you use the old syntax definition?

I'm not sure if I didn't downgrade properly but the problem didn't seem to stop on the old definitions, but it was vastly more infrequent. When I use plaintext or a simpler syntax definition, the file opens instantly with no load time at all.

>Additionally, do you have something periodically changing contents of `/etc/hosts`?

I'm using [Parallels Desktop](https://www.parallels.com), I'm not sure if that has anything to do with it but there's nothing I can think of that is modifying my hosts file automatically. Usually when there is a change to my hosts, sublime will ask me if I'd like to re-open the file but that usually only happens when I'm doing manual edits.

>Additionally, have you tried a fresh install to make sure no other packages are causing the issue

I haven't tried that yet, I did take a look at `Tools > Developer > Profile Plugins` after my last lag spree and I didn't see anything about this package mentioned.

@michaelblyons it's not a consistent problem for me either, it'll be fine for an hour, and then load the next 8 times I open the sublime window again, then be fine again for a bit, etc.

**Comment by michaelblyons** [comment]
> > Additionally, do you have something periodically changing contents of `/etc/hosts`?
> 
> I'm using [Parallels Desktop](https://www.parallels.com), I'm not sure if that has anything to do with it but there's nothing I can think of that is modifying my hosts file automatically.

I think Parallels _does_ change `/etc/hosts`, at least occasionally. I see an extra entry at the bottom when I start a VM, and it disappears when I suspend it. I do not know if it changes anything outside of transition states.

I experimented with `touch`ing and appending to my long test file, and that didn't seem to have any effect. I don't think I had changed the test file the 2 times I saw Apple's beach ball cursor.

**Comment by Nanorithm** [comment]
I've found a way to disable the issue with Parallels.

* Shutdown/exit parallels
* `sudo vi /Library/Preferences/Parallels/network.desktop.xml`
* Update `<NATDAllowEtcHostsWrite>1</NATDAllowEtcHostsWrite>` to `<NATDAllowEtcHostsWrite>0</NATDAllowEtcHostsWrite>`

This will disable parallels from being able to write to /etc/hosts for it's Shared Network mode.

**Comment by Nanorithm** [comment]
After playing with it for a few days, it looks like disabling the parallels write to the hosts file solved the problem, no more intermittent reloading that I've noticed. Thanks for all the help guys!
